### ISSUE TITLE
Add in partial Japanese translation from Launchpad

### ISSUE THREAD

**Issue by ExcaliburZero** [ExcaliburZero/jekyll-helper#42]
A while ago Rui914 translated some of Jekyll Helper into Japanese through Launchpad. The translation file should be exported from Launchpad and put into the GitHub repository.

@Rui914 If you could do this and submit it through a pull request that would be great. If you need any help doing it I can walk you through it. If you don't want to do then I could do it for you, but I'd rather you have the credit for the commit adding it since you did the translation.

**Comment by Rui914** [comment]
#43
